name: Final Cookbook Deployment

on:
  issues:
    types: [closed]

jobs:
  deploy-final:
    if: contains(github.event.issue.labels.*.name, 'add-repo')
    runs-on: ubuntu-latest

    env:
      ALLOWED_USERS: "katharinastarzer21"
      COOKBOOK_PATH: cookbooks/${{ github.event.issue.number }}

    steps:
      - name: Check if user is authorized to close the issue
        run: |
          echo "Closed by: ${{ github.actor }}"
          if [[ ",${ALLOWED_USERS}," != *",${{ github.actor }},"* ]]; then
            echo "User ${{ github.actor }} is not authorized to deploy."
            exit 1
          fi

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyyaml

      - name: Save issue body to file
        run: echo "${{ github.event.issue.body }}" > issue_body.txt

      - name: Parse issue and update notebook_gallery.yaml
        run: python parse_issue.py
        env:
          GITHUB_ENV: ${{ github.env }}

      - name: Clone submitted repository
        run: git clone $REPO_URL submitted_repo

      - name: Prepare submitted repo
        run: |
          if [ -f submitted_repo/README.md ] && [ ! -f submitted_repo/index.md ]; then
            cp submitted_repo/README.md submitted_repo/index.md
          fi

      - name: Build cookbook and gallery with Sphinx
        run: |
            mkdir -p cookbooks/$ROOT_PATH
            sphinx-build -b html submitted_repo cookbooks/$ROOT_PATH -c docs
            sphinx-build -b html docs _temp_gallery -c docs
            mkdir -p _site/cookbooks
            cp -r _temp_gallery/* _site/
            cp -r cookbooks/* _site/cookbooks/
            touch _site/.nojekyll

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git fetch origin gh-pages
          git checkout gh-pages
          git pull

          rm -rf cookbooks/
          cp -r _site/cookbooks ./
          cp _site/index.html ./
          cp _site/.nojekyll ./

          git add cookbooks/ index.html .nojekyll notebook_gallery.yaml
          git commit -m "Final deployment of cookbook $ROOT_PATH from issue #${{ github.event.issue.number }}" || echo "No changes"
          git push origin gh-pages
