name: Deploy MyST to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BASE_URL: /${{ github.event.repository.name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout MyST repo (PR branch)
        uses: actions/checkout@v4
        with:
          repository: jupyter-book/mystmd
          ref: feat/prototype-hidden-in-html
          path: mystmd

      - name: Cache mystmd node_modules
        uses: actions/cache@v4
        with:
          path: mystmd/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('mystmd/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install & build MyST
        working-directory: mystmd
        run: |
          npm ci
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
    
      - name: Install dependencies
        run: |
          pip install pyyaml nbformat

      - name: Clone external notebook repository
        run: python scripts/clone_sync_repos.py

      - name: Generate gallery markdown files
        run: python scripts/generate_gallery_md.py

      - name: Generate keywords markdown files
        run: python scripts/gallery_keywords.py

      - name: Generate Buttons in index file
        run: python scripts/indexbutton.py

      - name: Generate myst.yml and TOC
        run: python scripts/build_myst_yml.py

      - name: Build HTML Assets
        run: node ../mystmd/node_modules/mystmd/dist/myst.cjs build --execute --html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
